workflows:
  android-preview:
    name: Tosheh Akherat Android Preview

    environment:
      flutter: stable

    scripts:
      - name: Generate Android project
        script: |
          if [ ! -d "android" ]; then
            flutter create --platforms=android --project-name=tosheh_akhirat .
          fi

      - name: Get Flutter packages
        script: flutter pub get

      - name: Build Debug APK
        script: flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
